name: Psych_Chatbot
channels:
  - defaults
dependencies:
  - matplotlib=3.5.1
  - numpy=1.23.5
  - pip=23.0.1
  - python=3.10.2
  - pandas=1.3.5
  - json=2.0.9
  - collections
  - string
  - sklearn=1.0.2
  - os
  - sys
  - joblib=1.1.0
